# The URL the site will be built for
base_url = "https://martin-t.github.io"

# The site title and description; used in feeds by default. TODO
#title = ""
#description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# TODO atom vs rss? test feed works
generate_feed = true

# Whether to build a search index to be used later on by a JavaScript library
# LATER Use this
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Available themes: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
#highlight_theme = "base16-ocean-dark"
#highlight_theme = "boron"
#highlight_theme = "gruvbox-light"
#highlight_theme = "nyx-bold"
#highlight_theme = "solarized-light"
highlight_theme = "visual-studio-dark"
# In case I want a different VSC based theme, they're here butneed to be ported to tmTheme:
# https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_modern.json

[extra]
# Put all your custom variables here
