name: CI

# Note that GH Actions need to have write permissions for this to work:
# https://stackoverflow.com/a/72992289/2468852

on:
  push:
    branches:
      - master
  workflow_dispatch:
    # This allows running it on any branch manually:
    # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shalzz/zola-deploy-action@v0.18.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
